### ISSUE TITLE
The @Test methods are not executed properly if the @Before fails

### ISSUE THREAD

**Issue by SebastianAdams** [BBj-Plugins/BBjUnitTest#13]
If the @Before fails due to an Exception for instance, the @Test methods are all marked as passed, although they did not run. Either the @Test methods need to be marked as skipped, or also as failed test methods.

**Comment by hyyan** [comment]
@SebastianAdams Any update on this specific issue ? You cannot imagine how important this one is.
it misses up the whole test results.

**Comment by SebastianAdams** [comment]
Hi @hyyan, this issue is fixed in the latest version of the plug-in.

**Comment by hyyan** [comment]
@SebastianAdams Working as expected  , thanks for the update

**Comment by hyyan** [comment]
@SebastianAdams was too quick to close , this still not working for me , the following case crashes the plugin using BBj Nightly build 

```java


class public ClassTest

    rem @Before
    method public void setUp()
      throw "Error Message", 256
    methodend

    rem @Test
    method public void someTest()
      Assert.Equals(1 , 1)
    methodend

    rem @After
    method public void tearDown()
        rem #Instance! = null()
    methodend

classend

```
